# baseURL = "/"
relativeURLs = true
languageCode = "en-us"
title = "MSNE Journal Club"
theme = "kube"

description = "Neuroengineering Journal Club, created by students for studetns!"
Paginate = 4
[Params]
  author = "M.Sc. Neuroengineering"
  bio = "Technical University Munich"
  location = "Munich, Germany"
  RSSLink = "/index.xml"

  github = "https://github.com/neuroengineering" # add your github profile name
  email = " njc@lists.lrz.de"
  copyright  = """Powered by [Hugo](//gohugo.io). Theme by [jeblister](https://github.com/jeblister).
  <br/>Aleksandra Teska &bull;
  Technische Universität München &bull;
  Arcisstraße 21 &bull;
  80333 München
  """

[[menu.main]]
    name = "MSNE Blog"
    weight = -100
    url = "http://www.neuroengineering.blog"
[[menu.main]]
    name = "Talks"
    weight = -100
    url = "/talks/"
[[menu.main]]
    name = "About"
    weight = -100
    url = "/faq/"
